spring:
  application:
    name: member-service
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${PROFILE}

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
        registration:
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email
          naver:
            client-id: ${NAVER_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: ${NAVER_REDIRECT}
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - email
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT}
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - email

jwt:
  secret: ${JWT_SECRET_KEY}
  access:
    expiration: ${ACCESS_TOKEN_EXPIRED}
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRED}
