spring:
  application:
    name: apigateway-service

  config:
    import: optional:file:.env[.properties]

  cloud:
    gateway:
      routes:
        - id: game-service
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/api/admin/games
            - Path=/api/games

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/admin/members
            - Path=/api/members

    config:
      uri: http://43.202.255.139:8888
      name: config-service

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.202.255.139:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh, info, metrics, prometheus