#!/bin/sh
if [ -d "frontend" ]; then
  cd frontend && yarn test && yarn android || exit 1
  cd ..
fi

# backend 빌드
if [ -d "backend" ]; then
  cd backend/yarae/yarae && ./gradlew clean build || exit 1
fi
